export const mockAssets = [
  {
    id: '1',
    name: 'Commercial Property A',
    type: 'Real Estate',
    value: 1500000,
    status: 'published',
    createdAt: '2024-03-15',
    description: 'Prime commercial property located in the heart of the business district.',
    shortDescription: 'Prime commercial property in CBD',
    assetClass: 'Commercial Real Estate',
    subClass: 'Office Building',
    sector: 'Real Estate',
    region: 'North America',
    country: 'United States',
    location: 'New York, NY',
    managerName: 'John Smith',
    managerEmail: 'john.smith@example.com',
    managerPhone: '+1 (555) 123-4567',
    companyName: 'Smith Real Estate Management',
    regulatoryLicenses: ['SEC', 'FINRA'],
    targetValue: '1500000',
    minimumInvestment: '50000',
    expectedReturn: '12',
    investmentTerm: '60',
    currency: 'USD',
    paymentFrequency: 'Monthly',
    riskLevel: 'Medium',
    riskFactors: ['Market Risk', 'Liquidity Risk', 'Interest Rate Risk'],
    regulatoryCompliance: ['KYC', 'AML', 'FATCA'],
    investorRestrictions: 'Accredited investors only',
    occupancyRate: 95,
    tenants: 12,
    lastValuation: '2024-02-15',
    nextValuation: '2024-08-15',
    performance: {
      ytd: 8.5,
      oneYear: 12.3,
      threeYear: 35.7,
      fiveYear: 62.4
    },
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop'
  },
  // ... (keep the rest of the mock assets)
];